### ISSUE TITLE
"Failed to install" on latest update 

### ISSUE THREAD

**Issue by genmce** [davfive/obsidian-jtab#4]
Obsidian 0.14.6
Attempt to install 1.0.4 Obsidian jTab 
"Failed to install jTab"
*I am very interested in this*

I would really like to see and would like to help, if I am able, a [chordpro format ](https://www.chordpro.org/chordpro/chordpro-file-format-specification/)display interface for obsidian.  I have created a forum post [here](https://forum.obsidian.md/t/support-or-a-plugin-chordpro-format/35150)

I write my own songs and would love to use obsidian visualize links and common themes that will stimulate creativity.

**Comment by davfive** [comment]
@genmce, thanks for letting me know. I'll see what's going on and have a fix shortly.

I've used chordpro before. I chose jTab because it renders to html and not pdf. I am currently working on a css library that maps jTab notation straight to html/css (no svg). Including chordpro notation would be a fun addition.

**Comment by davfive** [comment]
@genmce, Fixed - I needed to create a 1.0.4 version. For some reason the Obsidian Community Plugins got the idea I had a 1.0.4 version. Now that it exists, it installed just fine. Thanks for reporting this.
